server {
  listen 80;

  # Auth service under /auth/...
  location /auth/ {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_pass http://auth:5001/;
  }

  # Shortener service under /shortener/...
  location /shortener/ {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_pass http://shortener:5000/;
  }
}